services:
    app1:
        build: ./app
        ports:
            - "5001:5000"
        volumes:
            - ./mensagens:/mensagens
            - ./certificados:/certificados
        networks:
            - rede_mensagens
        environment:
            - NOME_INSTANCIA=app1

    app2:
        build: ./app
        ports:
            - "5002:5000"
        volumes:
            - ./mensagens:/mensagens
            - ./certificados:/certificados
        networks:
            - rede_mensagens
        environment:
            - NOME_INSTANCIA=app2

    app3:
        build: ./app
        ports:
            - "5003:5000"
        volumes:
            - ./mensagens:/mensagens
            - ./certificados:/certificados
        networks:
            - rede_mensagens
        environment:
            - NOME_INSTANCIA=app3

volumes:
    mensagens:
    certificados:

networks:
    rede_mensagens:
        driver: bridge
